# Generated by Django 2.0.4 on 2018-09-14 14:33

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180913_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='time',
        ),
        migrations.AddField(
            model_name='like',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['created', 'article']),
        ),
    ]
